"""Auditable product capability catalog shown in the RepoVault UI."""

from __future__ import annotations

FEATURE_GROUPS: tuple[tuple[str, tuple[str, ...]], ...] = (
    (
        "Connect & branches",
        (
            "Canonical owner/repository parsing",
            "HTTPS GitHub URL parsing",
            "Public visibility verification",
            "Private repository rejection",
            "Two-step repository onboarding",
            "Up to 300 branch discovery",
            "Default branch prioritization",
            "Protected branch badges",
            "Branch commit SHA preview",
            "Branch selector search",
            "Default-branch fallback",
            "Localized connection errors",
        ),
    ),
    (
        "3D mobile experience",
        (
            "Generated cinematic 3D vault artwork",
            "Perspective hover depth",
            "Animated glass orbit rings",
            "Floating repository particles",
            "Glassmorphism control surfaces",
            "Animated gradient borders",
            "Responsive mobile stacking",
            "Large touch targets",
            "One-hand action layout",
            "Compact mobile typography",
            "Horizontal tab scrolling",
            "Reduced-motion accessibility fallback",
        ),
    ),
    (
        "Repository explorer",
        (
            "Immutable commit-pinned workspace",
            "20,000-file recursive index",
            "Complete-tree path search",
            "Twenty-term search matching",
            "500-character search ceiling",
            "160-card mobile pages",
            "Paginated 500-row metadata table",
            "Multi-select checkbox file cards",
            "One-tap first-20 visible selection",
            "Tap-first file preview",
            "Package-first smart sorting",
            "Language detection",
            "Blob SHA display",
            "Human-readable file sizes",
            "Potential secret-path status",
            "Empty-file support",
            "Historical snapshot explorer reuse",
        ),
    ),
    (
        "Smart file groups",
        (
            "APK detection",
            "Android App Bundle detection",
            "IPA package detection",
            "Desktop installer detection",
            "Linux package detection",
            "Source-code grouping",
            "Archive grouping",
            "Image and media grouping",
            "Documentation grouping",
            "Test-file grouping",
            "Config and CI grouping",
            "Data-file grouping",
        ),
    ),
    (
        "Downloads",
        (
            "Individual exact-blob download",
            "Binary-file download",
            "Text-file download",
            "25 MB individual ceiling",
            "Selected-file ZIP",
            "Twenty-file bundle ceiling",
            "50 MB selected input ceiling",
            "Traversal-safe ZIP paths",
            "Bundle provenance manifest",
            "Partial ZIP cleanup",
            "Complete website-hosted source ZIP",
            "500 MB streamed archive ceiling",
            "ZIP central-directory integrity validation",
            "Two-hour temporary retention",
            "Two-gigabyte temporary storage budget",
            "Randomized private filenames",
            "Restrictive file permissions",
        ),
    ),
    (
        "History & snapshots",
        (
            "Latest 50 commits",
            "Commit author display",
            "Commit date display",
            "Commit message display",
            "Signature verification status",
            "Changed-file status",
            "Addition counts",
            "Deletion counts",
            "Rename source path",
            "Commit archive identity",
            "One-tap historical browsing",
            "Historical individual download",
            "Historical selected ZIP",
            "Historical complete ZIP",
        ),
    ),
    (
        "Releases & app files",
        (
            "Published release discovery",
            "Prerelease badges",
            "Release tag display",
            "Release publication time",
            "APK asset emphasis",
            "AAB asset emphasis",
            "ZIP asset emphasis",
            "Asset MIME type",
            "Asset byte size",
            "Asset download count",
            "Repository-scoped URL validation",
            "Release source ZIP",
            "Release source TAR.GZ",
            "Twenty-release ceiling",
        ),
    ),
    (
        "GitHub Actions",
        (
            "Public workflow-run discovery",
            "Workflow name display",
            "Run-number display",
            "Event display",
            "Branch display",
            "Run status display",
            "Run conclusion display",
            "Retained artifact listing",
            "Artifact ZIP size",
            "Artifact expiry display",
            "Expired artifact badge",
            "Official authenticated download handoff",
        ),
    ),
    (
        "Snapshot intelligence",
        (
            "Category distribution summary",
            "Largest-file leaderboard",
            "Repository source-size total",
            "Release count",
            "Release-asset count",
            "Workflow-run count",
            "Commit count",
            "Protected-branch count",
            "Current branch identity",
            "Exact commit identity",
            "Archived-repository status",
            "Star count display",
        ),
    ),
    (
        "Safety & reliability",
        (
            "Fixed API host allowlist",
            "Fixed codeload host allowlist",
            "Redirect rejection",
            "No visitor token collection",
            "No private repository proxy",
            "No source execution",
            "No APK execution",
            "No archive extraction",
            "No repository clone",
            "No shell or subprocess",
            "No package installation",
            "No workflow dispatch",
            "Sensitive filename blocking",
            "Per-operation byte ceilings",
            "Short TTL/LRU cache",
            "GitHub rate-limit messaging",
            "Malformed API response rejection",
            "Ephemeral output cleanup",
        ),
    ),
    (
        "AI review workspace",
        (
            "Comprehensive review mode",
            "Bug-hunt mode",
            "Defensive security mode",
            "Performance mode",
            "Architecture mode",
            "Test-strategy mode",
            "Documentation mode",
            "Quick depth",
            "Standard depth",
            "Deep depth",
            "Branch comparison",
            "Relevance-ranked evidence",
            "Secret redaction",
            "Prompt-injection neutralization",
            "Static findings without GPU",
            "Qwen Coder ZeroGPU review",
            "Graceful ZeroGPU registration fallback",
            "Review refinement",
            "Markdown export",
            "Validated patch export",
            "Machine-readable JSON export",
        ),
    ),
)

FEATURE_COUNT = sum(len(features) for _, features in FEATURE_GROUPS)


def render_feature_catalog() -> str:
    lines = [
        f"## {FEATURE_COUNT}+ production capabilities",
        "",
        "Every item below maps to a visible interface behavior or an enforced backend control—no artificial code padding.",
    ]
    index = 1
    for title, features in FEATURE_GROUPS:
        lines.extend(("", f"### {title}", ""))
        for feature in features:
            lines.append(f"- **{index:03d}** · {feature}")
            index += 1
    return "\n".join(lines)
